name: CI

on:
  pull_request:
    types: ["opened", "edited", "synchronize", "reopened"]
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14']

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run `generate`
        run: yarn generate

      - name: Run `lint`
        run: yarn lint

      - name: Run `typecheck`
        run: yarn typecheck
