name: deploy-prod

on:
  push:
    branches: [main]

jobs:
  deploy-server:
    runs-on: ubuntu-latest

    environment:
      name: Production

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: determine what need to be deployed
        run: |
          if ! git diff HEAD^ HEAD --quiet ./packages/vlepo-shared; then
              echo "DEPLOY_SHARED=true" >> "$GITHUB_ENV"
          fi
          if ! git diff HEAD^ HEAD --quiet ./packages/vlepo-server; then
              echo "DEPLOY_SERVER=true" >> "$GITHUB_ENV"
          fi

      - name: use Node.js 14
        if: env.DEPLOY_SHARED == 'true' || env.DEPLOY_SERVER == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
          scope: '@vlepo'

      - name: install dependencies
        if: env.DEPLOY_SHARED == 'true' || env.DEPLOY_SERVER == 'true'
        run: yarn --frozen-lockfile

      - name: deploy shared
        if: env.DEPLOY_SHARED == 'true'
        run: yarn run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: build server
        if: env.DEPLOY_SERVER == 'true'
        run: yarn build:server

      - name: deploy server
        if: env.DEPLOY_SERVER == 'true'
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy-server.yml
          directory: ./ansible-playbooks/
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [web]
            ${{secrets.SERVER_URL}} ansible_port=${{secrets.SERVER_SSH_PORT}}

  deploy-client:
    runs-on: ubuntu-latest

    environment:
      name: Production

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: determine what need to be deployed
        run: |
          if ! git diff HEAD^ HEAD --quiet ./packages/vlepo-client; then
              echo "DEPLOY_CLIENT=true" >> "$GITHUB_ENV"
          fi

      - name: deploy client
        if: env.DEPLOY_CLIENT == 'true'
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-comment: false
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
